media:
  - name: project_images
    label: Project images
    input: public/projects
    output: /projects
    categories: [image]
    rename: safe

content:
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    subfolders: true
    filename: "{primary}/index.md"
    view:
      primary: title
      sort: date
      order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: summary
        label: Summary
        type: text
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: draft
        label: Draft
        type: boolean
      - name: tags
        label: Tags
        type: select
        options:
          values: [Backend, FrontEnd, FullStack, Machine Learning, Mobile, New, UI UX]
          multiple: true
          placeholder: Select existing tags
        required: true
      - name: customTags
        label: Custom tags
        type: string
        list: true
      - name: demoUrl
        label: Demo URL
        type: string
      - name: repoUrl
        label: Repository URL
        type: string
      - name: coverImage
        label: Cover image
        type: image
        options:
          media: project_images
          path: projects
          extensions: [png, jpg, jpeg, webp, avif]
          rename: safe
      - name: body
        label: Content
        type: rich-text
        options:
          format: markdown
          media: project_images
          path: projects
          rename: safe
          switcher: true
    operations:
      create: true
      update: true
      delete: true
