export const cardData = [
    {
        title: "Programming Language",
        items: [
            { name: "JavaScript", image: "skills/javascript.svg", alt: "JavaScript logo" },
            { name: "TypeScript", image: "skills/typescript.svg", alt: "typeScript logo" },
            { name: "Kotlin", image: "skills/kotlin.svg", alt: "kotlin logo" },
            { name: "PHP", image: "skills/php.svg", alt: "PHP logo" },
            { name: "HTML", image: "skills/html.svg", alt: "HTML logo" },
            { name: "CSS", image: "skills/css.svg", alt: "CSS logo" },
        ]
    },
    {
        title: "Framework | Library",
        items: [
            { name: "Express", image: "skills/express.svg", alt: "Express logo" },
            { name: "Next JS", image: "skills/next.svg", alt: "Next logo" },
            { name: "Vite JS", image: "skills/vite.svg", alt: "Vite logo" },
            { name: "Astro", image: "skills/astro.svg", alt: "Astro logo" },
            { name: "Tailwind CSS", image: "skills/tailwind.svg", alt: "Tailwind logo" },
            { name: "Bootstrap", image: "skills/bootstrap.svg", alt: "Bootstrap logo" },
        ]
    },
    {
        title: "Machine Learning",
        items: [
            { name: "Python", image: "skills/python.svg", alt: "Python logo" },
            { name: "Jupyter", image: "skills/j-note.svg", alt: "Jupyter logo" },
            { name: "TensorFlow", image: "skills/tensorflow.svg", alt: "TensorFlow logo" },
            { name: "Scikit-learn", image: "skills/sklearn.svg", alt: "Scikit-learn logo" },
            { name: "Pandas", image: "skills/pandas.svg", alt: "Pandas logo" },
            { name: "Numpy", image: "skills/numpy.svg", alt: "Numpy logo" },
        ]
    },
    {
        title: "Cloud & DevOps",
        items: [
            { name: "Google Cloud Platform", image: "skills/gcp.svg", alt: "GCP logo" },
            { name: "Alibaba Cloud", image: "skills/alibaba.svg", alt: "ALIBABA logo" },
            { name: "Amazon Web Services", image: "skills/aws.svg", alt: "AWS logo" },
            { name: "Docker", image: "skills/docker.svg", alt: "Docker logo" },
            { name: "Kubernetes", image: "skills/kubernetes.svg", alt: "Kubernetes logo" },
            { name: "GitHub Actions", image: "skills/github.svg", alt: "GitHub Actions logo" },
        ]
    },
    {
        title: "Mobile Development",
        items: [
            { name: "React Native", image: "skills/react.svg", alt: "React Native logo" },
            { name: "Kotlin Multiplatform", image: "skills/kotlin.svg", alt: "Kotlin logo" },
        ]
    },
    {
        title: "Design | UI/UX",
        items: [
            { name: "Figma", image: "skills/figma.svg", alt: "Figma logo" },
            { name: "Lunacy", image: "skills/lunacy.svg", alt: "Lunacy logo" },
            { name: "Adobe XD", image: "skills/xd.svg", alt: "Adobe XD logo" },
        ]
    },
    {
        title: "Database | Storage",
        items: [
            { name: "Firebase", image: "skills/firebase.svg", alt: "Firebase logo" },
            { name: "MongoDB", image: "skills/mongo.svg", alt: "MongoDB logo" },
            { name: "Supabase", image: "skills/supabase.svg", alt: "Supabase logo" },
            { name: "MySQL", image: "skills/mysql.svg", alt: "MySQL logo" },
        ]
    },
]
export const certificateData = [
    // top certificate
    {
        id: 1,
        name: "Google Cybersecurity",
        provider: "Coursera",
        image: "certificates/Coursera7.png",
        date: "Aug 3 2024",
        link: "https://coursera.org/verify/professional-cert/M1GA8S0DBG01",
        pinned: true,
    },
    {
        id: 39,
        name: "Alibaba Cloud Certified Developers",
        provider: "Alibaba Cloud",
        image: "certificates/alibaba.png",
        date: "Jul 29 2024",
        link: "https://alicloud-common.oss-ap-southeast-1.aliyuncs.com/2023/Developers/Certified-Developer.jpg",
        pinned: true,
    },
    {
        id: 2,
        name: "Graduated from Bangkit 2024, a Google-led program in collaboration with GoTo, Tokopedia, and Traveloka in Cloud Computing learning path",
        provider: "Bangkit Academy",
        image: "certificates/bangkit.png",
        date: "Jul 10 2024",
        link: "https://drive.google.com/file/d/1rcbeNV4USyhwUZv9C1S8dzOQytxonw8e/view",
        pinned: true,
    },
    {
        id: 71,
        name: "Google Cloud Architect",
        provider: "Dicoding",
        image: "certificates/dicoding12.png",
        date: "Nov 15 2024",
        link: "https://www.dicoding.com/certificates/NVP743Y0OPR0",
        pinned: true,
    },
    {
        id: 4,
        name: "Google IT Support",
        provider: "Coursera",
        image: "certificates/it_support.png",
        date: "March 12 2024",
        link: "https://coursera.org/verify/professional-cert/ZJ2CZ5UY3P77",
        pinned: true,
    },
    {
        id: 41,
        name: "Studi Independen Bersetifikat Angkatan 6",
        provider: "MSIB",
        image: "certificates/msib.png",
        date: "June 30, 2024",
        link: "https://kampusmerdeka.kemdikbud.go.id/cert/d9aa2ecfff7b1e1addb456ce53bb9d634ddc298d944383",
        pinned: true,
    },
    {
        id: 47,
        name: "English for Business Communication",
        provider: "Bangkit Academy",
        image: "certificates/tbi.png",
        date: "July 12, 2024",
        link: "#",
    },
    // Coursera certificates
    {
        id: 5,
        name: "IT Security: Defense against the digital dark arts",
        provider: "Coursera",
        image: "certificates/coursera2.png",
        date: "Mar, 12 2024",
        link: "https://coursera.org/verify/JKUX57YS3LDG",
    },
    {
        id: 6,
        name: "System Administration and IT Infrastructure Services",
        provider: "Coursera",
        image: "certificates/coursera3.png",
        date: "Feb, 22 2024",
        link: "https://coursera.org/verify/BVGLJ2YTNK25",
    },
    {
        id: 7,
        name: "Technical Support Fundamentals",
        provider: "Coursera",
        image: "certificates/coursera4.png",
        date: "Feb, 23 2024",
        link: "https://coursera.org/verify/F6XFRJE63KWV",
    },
    {
        id: 8,
        name: "The Bits and Bytes of Computer Networking",
        provider: "Coursera",
        image: "certificates/coursera5.png",
        date: "Feb, 20 2024",
        link: "https://coursera.org/verify/W29JM3UU2RPQ",
    },
    {
        id: 9,
        name: "Operating Systems and You : Becoming a Power User",
        provider: "Coursera",
        image: "certificates/coursera6.png",
        date: "Mar, 12 2024",
        link: "https://coursera.org/verify/QE2P65GSJ4NE",
    },
    {
        id: 42,
        name: "Put It to Work: Prepare for Cybersecurity Jobs",
        provider: "Coursera",
        image: "certificates/coursera8.png",
        date: "Aug, 3 2024",
        link: "https://coursera.org/verify/S0T7NEHLC1IC",
    },
    {
        id: 43,
        name: "Automate Cybersecurity Tasks with Python",
        provider: "Coursera",
        image: "certificates/coursera9.png",
        date: "July, 30 2024",
        link: "https://coursera.org/verify/X8CFNS6SH88V",
    },
    {
        id: 44,
        name: "Sound the Alarm: Detection and Response",
        provider: "Coursera",
        image: "certificates/coursera10.png",
        date: "July, 25 2024",
        link: "https://coursera.org/verify/CUTEMYEBRRS4",
    },
    {
        id: 45,
        name: "Assets, Threats, and Vu lnerabilities",
        provider: "Coursera",
        image: "certificates/coursera11.png",
        date: "July, 22 2024",
        link: "https://coursera.org/verify/HKJBS4QT77QJ",
    },
    {
        id: 46,
        name: "Tools of the Trade: Linu x and SQL",
        provider: "Coursera",
        image: "certificates/coursera12.png",
        date: "July, 19 2024",
        link: "https://coursera.org/verify/TRTPM29FRJ55",
    },
    // Dicoding certificates
    {
        id: 10,
        name: "Belajar Dasar Git dengan GitHub",
        provider: "Dicoding",
        image: "certificates/dicoding1.png",
        date: "Feb 19, 2024",
        link: "https://www.dicoding.com/certificates/98XW2QJVWPM3",
    },
    {
        id: 11,
        name: "Belajar Dasar Pemrograman Web",
        provider: "Dicoding",
        image: "certificates/dicoding2.png",
        date: "Feb, 29 2024",
        link: "https://www.dicoding.com/certificates/NVP77VV4OPR0",
    },
    {
        id: 12,
        name: "Belajar Membuat Aplikasi Back-End untuk Pemula",
        provider: "Dicoding",
        image: "certificates/dicoding3.png",
        date: "Nov, 30 2022",
        link: "https://www.dicoding.com/certificates/1OP85NWOQPQK",
    },
    {
        id: 13,
        name: "Belajar Penerapan Machine Learning dengan Google Cloud",
        provider: "Dicoding",
        image: "certificates/dicoding4.png",
        date: "May, 16 2024",
        link: "https://www.dicoding.com/certificates/72ZDV7VWLZYW",
    },
    {
        id: 14,
        name: "Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)",
        provider: "Dicoding",
        image: "certificates/dicoding5.png",
        date: "Oct, 12 2022",
        link: "https://www.dicoding.com/certificates/MRZM458R3XYQ",
    },
    {
        id: 15,
        name: "Memulai Dasar Pemrograman untuk Menjadi Pengembang Software",
        provider: "Dicoding",
        image: "certificates/dicoding6.png",
        date: "Feb, 19 2024",
        link: "https://www.dicoding.com/certificates/6RPNV9285Z2M",
    },
    {
        id: 16,
        name: "Memulai Pemrograman Dengan Kotlin",
        provider: "Dicoding",
        image: "certificates/dicoding7.png",
        date: "Sept, 15 2023",
        link: "https://www.dicoding.com/certificates/0LZ0QG1O0Z65",
    },
    {
        id: 17,
        name: "Menjadi Google Cloud Engineer",
        provider: "Dicoding",
        image: "certificates/dicoding8.png",
        date: "May, 8 2024",
        link: "https://www.dicoding.com/certificates/MRZME42D3PYQ",
    },
    {
        id: 18,
        name: "Pengenalan ke Logika Pemrograman (Programming Logic 101)",
        provider: "Dicoding",
        image: "certificates/dicoding9.png",
        date: "Feb, 19 2024",
        link: "https://www.dicoding.com/certificates/GRX5QYE5KZ0M",
    },
    {
        id: 19,
        name: "Belajar Dasar Pemrograman JavaScript",
        provider: "Dicoding",
        image: "certificates/dicoding10.png",
        date: "Oct, 26 2022",
        link: "https://www.dicoding.com/certificates/81P28G8LYPOY",
    },
    {
        id: 61,
        name: "Belajar Dasar Manajemen Proyek",
        provider: "Dicoding",
        image: "certificates/dicoding11.png",
        date: "Aug 9, 2024",
        link: "https://www.dicoding.com/certificates/JLX17ERENX72",
    },
    {
        id: 63,
        name: "Belajar Dasar Data Science",
        provider: "Dicoding",
        image: "certificates/image.png",
        date: "Sep 5, 2024",
        link: "https://www.dicoding.com/certificates/QLZ97YEYMP5D",
    },
    {
        id: 64,
        name: "Belajar Dasar Structured Query Language (SQL)",
        provider: "Dicoding",
        image: "certificates/image2.png",
        date: "Sep 5, 2024",
        link: "https://www.dicoding.com/certificates/EYX4VNE4JZDL",
    },
    {
        id: 65,
        name: "Belajar Strategi Pengembangan Diri",
        provider: "Dicoding",
        image: "certificates/image3.png",
        date: "Sep 12, 2024",
        link: "https://www.dicoding.com/certificates/NVP7Q28QVZR0",
    },
    {
        id: 72,
        name: "Memulai Pemrograman dengan Python",
        provider: "Dicoding",
        image: "certificates/dicoding13.png",
        date: "Nov 23, 2024",
        link: "https://www.dicoding.com/certificates/81P24MR88ZOY",
    },
    {
        id: 73,
        name: "Belajar Dasar AI",
        provider: "Dicoding",
        image: "certificates/dicoding14.png",
        date: "Nov 28, 2024",
        link: "https://www.dicoding.com/certificates/4EXG72E8GPRL",
    },
    {
        id: 74,
        name: "Belajar Machine Learning untuk Pemula",
        provider: "Dicoding",
        image: "certificates/dicoding15.png",
        date: "Dec 16, 2024",
        link: "https://www.dicoding.com/certificates/0LZ04LNMRP65",
    },
    
    // Codepolitan certificates
    {
        id: 48,
        name: "Belajar Dasar HTML",
        provider: "Codepolitan",
        image: "certificates/codepolitan1.png",
        date: "July, 30 2024",
        link: "https://codepolitan.com/c/MJ0HYRW",
    },
    {
        id: 49,
        name: "Belajar Dasar CSS",
        provider: "Codepolitan",
        image: "certificates/codepolitan2.png",
        date: "July, 31 2024",
        link: "https://codepolitan.com/c/DKE3UFB",
    },
    {
        id: 50,
        name: "Belajar Bootstrap CSS Framework",
        provider: "Codepolitan",
        image: "certificates/codepolitan3.png",
        date: "Aug, 1 2024",
        link: "https://codepolitan.com/c/JVLB3KF",
    },
    {
        id: 51,
        name: "Membuat Halaman Website Portofolio Menggunakan Tailwind CSS",
        provider: "Codepolitan",
        image: "certificates/codepolitan4.png",
        date: "Aug, 1 2024",
        link: "https://codepolitan.com/c/GHWAD0I",
    },
    {
        id: 52,
        name: "Belajar JavaScript",
        provider: "Codepolitan",
        image: "certificates/codepolitan5.png",
        date: "Aug, 2 2024",
        link: "https://codepolitan.com/c/8ZICBQK",
    },
    {
        id: 52,
        name: "Belajar JavaScript DOM",
        provider: "Codepolitan",
        image: "certificates/codepolitan6.png",
        date: "Aug, 2 2024",
        link: "https://codepolitan.com/c/JHPNC8W",
    },
    {
        id: 53,
        name: "Belajar JavaScript Asynchronous",
        provider: "Codepolitan",
        image: "certificates/codepolitan7.png",
        date: "Aug, 4 2024",
        link: "https://codepolitan.com/c/GF1BV5A",
    },
    {
        id: 54,
        name: "Belajar Ajax dan Web API",
        provider: "Codepolitan",
        image: "certificates/codepolitan8.png",
        date: "Aug, 4 2024",
        link: "https://codepolitan.com/c/C90DLBK",
    },
    {
        id: 55,
        name: "Belajar Konsep OOP di Javascript",
        provider: "Codepolitan",
        image: "certificates/codepolitan9.png",
        date: "Aug, 5 2024",
        link: "https://codepolitan.com/c/OYVIIZT",
    },
    {
        id: 56,
        name: "Belajar React JS",
        provider: "Codepolitan",
        image: "certificates/codepolitan10.png",
        date: "Aug, 5 2024",
        link: "https://codepolitan.com/c/2D8HXWT",
    },
    {
        id: 57,
        name: "React.js 101 - Membuat dan Menggunakan Komponen dalam Aplikasi Berbasis React.js",
        provider: "Codepolitan",
        image: "certificates/codepolitan11.png",
        date: "Aug, 7 2024",
        link: "https://codepolitan.com/c/32S5K1B",
    },
    {
        id: 58,
        name: "React.js State - Mengelola Perubahan Tampilan dengan Data bersama Event Handler",
        provider: "Codepolitan",
        image: "certificates/codepolitan12.png",
        date: "Aug, 7 2024",
        link: "https://codepolitan.com/c/IPQW1NH",
    },
    {
        id: 59,
        name: "React.js State Management - Panduan Menggunakan State yg Baik",
        provider: "Codepolitan",
        image: "certificates/codepolitan13.png",
        date: "Aug, 7 2024",
        link: "https://codepolitan.com/c/EOWS7UD",
    },
    {
        id: 70,
        name: "React.js - Membuat Aplikasi Split Bill",
        provider: "Codepolitan",
        image: "certificates/codepolitan14.png",
        date: "Jan, 4 2025",
        link: "https://codepolitan.com/c/4RBDB2Z",
    },
    {
        id: 71,
        name: "React.js - Belajar Lebih Dalam Tentang Component dan Jenisnya",
        provider: "Codepolitan",
        image: "certificates/codepolitan15.png",
        date: "Jan, 4 2025",
        link: "https://codepolitan.com/c/XL5H2WE",
    },
    {
        id: 72,
        name: "React.js - Bagaimana React.js Bekerja di Balik Layar",
        provider: "Codepolitan",
        image: "certificates/codepolitan16.png",
        date: "Jan, 4 2025",
        link: "https://codepolitan.com/c/UYHCNPR",
    },
    {
        id: 73,
        name: "React.js - Belajar Hook Effect dan Data Fetching",
        provider: "Codepolitan",
        image: "certificates/codepolitan17.png",
        date: "Jan, 4 2025",
        link: "https://codepolitan.com/c/TUCO9US",
    },
    // Udemy certificates
    {
        id: 62,
        name: "React Native Unveiled: From Basics to Mobile Mastery",
        provider: "Udemy",
        image: "certificates/Udemy React Native Unveiled: From Basics to Mobile Mastery.jpg",
        date: "Aug 8, 2024",
        link: "https://ude.my/UC-5bc1773d-ee4a-4337-a62c-596ae82bf238",
    },
    {
        id: 63,
        name: "User Experience Design - Learn UI UX App Design with Figma",
        provider: "Udemy",
        image: "certificates/Udemy User Experience Design - Learn UI UX App Design with Figma.jpg",
        date: "Aug 12, 2024",
        link: "https://ude.my/UC-0242cc0d-4e6b-4694-a902-ba22093f90d1",
    },
    {
        id: 62,
        name: "Cloud Computing and Amazon Web Services (AWS) Fundamentals",
        provider: "Udemy",
        image: "certificates/Udemy Cloud Computing and Amazon Web Services (AWS) Fundamentals.jpg",
        date: "Aug 12, 2024",
        link: "https://ude.my/UC-91de3e3a-79fe-463e-a5f5-53d3013a9ac5",
    },
]
