export const cardData = [
    {
        title: "Programming Language",
        items: [
            { name: "JavaScript", image: "skills/javascript.svg", alt: "JavaScript logo" },
            { name: "TypeScript", image: "skills/typescript.svg", alt: "typeScript logo" },
            { name: "Kotlin", image: "skills/kotlin.svg", alt: "kotlin logo" },
            { name: "PHP", image: "skills/php.svg", alt: "PHP logo" },
            { name: "HTML", image: "skills/html.svg", alt: "HTML logo" },
            { name: "CSS", image: "skills/css.svg", alt: "CSS logo" },
        ]
    },
    {
        title: "Framework | Library",
        items: [
            { name: "Express", image: "skills/express.svg", alt: "Express logo" },
            { name: "Next JS", image: "skills/next.svg", alt: "Next logo" },
            { name: "Vite JS", image: "skills/vite.svg", alt: "Vite logo" },
            { name: "Astro", image: "skills/astro.svg", alt: "Astro logo" },
            { name: "Tailwind CSS", image: "skills/tailwind.svg", alt: "Tailwind logo" },
            { name: "Bootstrap", image: "skills/bootstrap.svg", alt: "Bootstrap logo" },
        ]
    },
    {
        title: "Database | Storage",
        items: [
            { name: "Firebase", image: "skills/firebase.svg", alt: "Firebase logo" },
            { name: "MongoDB", image: "skills/mongo.svg", alt: "MongoDB logo" },
            { name: "Supabase", image: "skills/supabase.svg", alt: "Supabase logo" },
            { name: "MySQL", image: "skills/mysql.svg", alt: "MySQL logo" },
        ]
    },
    {
        title: "Cloud Computing",
        items: [
            { name: "Google Cloud Platform", image: "skills/gcp.svg", alt: "GCP logo" },
            { name: "Amazon Web Services", image: "skills/aws.svg", alt: "AWS logo" },
        ]
    },
    {
        title: "Design | UI/UX",
        items: [
            { name: "Figma", image: "skills/figma.svg", alt: "Figma logo" },
            { name: "Lunacy", image: "skills/lunacy.svg", alt: "Lunacy logo" },
            { name: "Adobe XD", image: "skills/xd.svg", alt: "Adobe XD logo" },
        ]
    },
]

export const certificateData = [
    {
        id: 2,
        name: "Studi Independen Bersetifikat Angkatan 6",
        provider: "MSIB",
        image: "certificates/msib.png",
        date: "June 30, 2024",
        link: "https://kampusmerdeka.kemdikbud.go.id/cert/d9aa2ecfff7b1e1addb456ce53bb9d634ddc298d944383",
    },
    {
        id: 3,
        name: "Google Cloud Computing Foundations Certificate",
        provider: "Google Cloud Skills Boost",
        image: "certificates/google-cloud-computing-foundations-certificate.png",
        date: "Apr 18, 2024",
        link: "https://www.credly.com/badges/a9035dc6-4b0d-40b4-abab-cb61cd74d3ba/public_url",
    },
    {
        id: 4,
        name: "Google IT Support",
        provider: "Coursera",
        image: "certificates/it_support.png",
        date: "2024-03-12",
        link: "https://coursera.org/verify/professional-cert/ZJ2CZ5UY3P77",
    },
    {
        id: 5,
        name: "IT Security: Defense against the digital dark arts",
        provider: "Coursera",
        image: "certificates/coursera2.png",
        date: "2024-03-12",
        link: "https://coursera.org/verify/JKUX57YS3LDG",
    },
    {
        id: 6,
        name: "System Administration and IT Infrastructure Services",
        provider: "Coursera",
        image: "certificates/coursera3.png",
        date: "2024-02-22",
        link: "https://coursera.org/verify/BVGLJ2YTNK25",
    },
    {
        id: 7,
        name: "Technical Support Fundamentals",
        provider: "Coursera",
        image: "certificates/coursera4.png",
        date: "2024-02-23",
        link: "https://coursera.org/verify/F6XFRJE63KWV",
    },
    {
        id: 8,
        name: "The Bits and Bytes of Computer Networking",
        provider: "Coursera",
        image: "certificates/coursera5.png",
        date: "2024-02-20",
        link: "https://coursera.org/verify/W29JM3UU2RPQ",
    },
    {
        id: 9,
        name: "Operating Systems and You : Becoming a Power User",
        provider: "Coursera",
        image: "certificates/coursera6.png",
        date: "2024-03-12",
        link: "https://coursera.org/verify/QE2P65GSJ4NE",
    },
    {
        id: 10,
        name: "Belajar Dasar Git dengan GitHub",
        provider: "Dicoding",
        image: "certificates/dicoding1.png",
        date: "2024-02-19",
        link: "https://www.dicoding.com/certificates/98XW2QJVWPM3",
    },
    {
        id: 11,
        name: "Belajar Dasar Pemrograman Web",
        provider: "Dicoding",
        image: "certificates/dicoding2.png",
        date: "2024-02-29",
        link: "https://www.dicoding.com/certificates/NVP77VV4OPR0",
    },
    {
        id: 12,
        name: "Belajar Membuat Aplikasi Back-End untuk Pemula",
        provider: "Dicoding",
        image: "certificates/dicoding3.png",
        date: "2022-11-30",
        link: "https://www.dicoding.com/certificates/1OP85NWOQPQK",
    },
    {
        id: 13,
        name: "Belajar Penerapan Machine Learning dengan Google Cloud",
        provider: "Dicoding",
        image: "certificates/dicoding4.png",
        date: "2024-05-16",
        link: "https://www.dicoding.com/certificates/72ZDV7VWLZYW",
    },
    {
        id: 14,
        name: "Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)",
        provider: "Dicoding",
        image: "certificates/dicoding5.png",
        date: "2022-10-12",
        link: "https://www.dicoding.com/certificates/MRZM458R3XYQ",
    },
    {
        id: 15,
        name: "Memulai Dasar Pemrograman untuk Menjadi Pengembang Software",
        provider: "Dicoding",
        image: "certificates/dicoding6.png",
        date: "2024-02-19",
        link: "https://www.dicoding.com/certificates/6RPNV9285Z2M",
    },
    {
        id: 16,
        name: "Memulai Pemrograman Dengan Kotlin",
        provider: "Dicoding",
        image: "certificates/dicoding7.png",
        date: "2023-09-15",
        link: "https://www.dicoding.com/certificates/0LZ0QG1O0Z65",
    },
    {
        id: 17,
        name: "Menjadi Google Cloud Engineer",
        provider: "Dicoding",
        image: "certificates/dicoding8.png",
        date: "2024-05-08",
        link: "https://www.dicoding.com/certificates/MRZME42D3PYQ",
    },
    {
        id: 18,
        name: "Pengenalan ke Logika Pemrograman (Programming Logic 101)",
        provider: "Dicoding",
        image: "certificates/dicoding9.png",
        date: "2024-02-19",
        link: "https://www.dicoding.com/certificates/GRX5QYE5KZ0M",
    },
    {
        id: 19,
        name: "Belajar Dasar Pemrograman JavaScript",
        provider: "Dicoding",
        image: "certificates/dicoding10.png",
        date: "2022-10-26",
        link: "https://www.dicoding.com/certificates/81P28G8LYPOY",
    },
    {
        id: 20,
        name: "Cloud Computing Fundamentals",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb1.png",
        date: "Mar 1, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/9060162",
    },
    {
        id: 21,
        name: "Infrastructure in Google Cloud",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb2.png",
        date: "Mar 5, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8224331",
    },
    {
        id: 22,
        name: "Networking & Security in Google Cloud",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb3.png",
        date: "Mar 7, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8249236",
    },
    {
        id: 23,
        name: "Data, ML, and AI in Google Cloud",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb4.png",
        date: "Mar 9, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8265125",
    },
    {
        id: 24,
        name: "Implement Load Balancing on Compute Engine",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb5.png",
        date: "Mar 9, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8266920",
    },
    {
        id: 25,
        name: "Set Up an App Dev Environment on Google Cloud",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb6.png",
        date: "Mar 10, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8274972",
    },
    {
        id: 26,
        name: "Build a Secure Google Cloud Network",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb7.png",
        date: "Mar 10, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8276088",
    },
    {
        id: 27,
        name: "Prepare Data for ML APIs on Google Cloud",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb8.png",
        date: "Mar 10, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8276653",
    },
    {
        id: 28,
        name: "Preparing for Your Associate Cloud Engineer Journey",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb9.png",
        date: "Mar 18, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8367217",
    },
    {
        id: 29,
        name: "Core Infrastructure",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb10.png",
        date: "Mar 20, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8384146",
    },
    {
        id: 30,
        name: "Essential Google Cloud Infrastructure: Foundation",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb11.png",
        date: "Mar 22, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8408418",
    },
    {
        id: 31,
        name: "Essential Google Cloud Infrastructure: Core Services",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb12+.png",
        date: "Mar 25, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8431369",
    },
    {
        id: 32,
        name: "Elastic Google Cloud Infrastructure: Scaling and Automation",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb13.png",
        date: "Mar 28, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8467245",
    },
    {
        id: 33,
        name: "Getting Started with Google Kubernetes Engine",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb14.png",
        date: "Mar 31, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8505216",
    },
    {
        id: 34,
        name: "Logging and Monitoring in Google Cloud",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb15.png",
        date: "Apr 1, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8514243",
    },
    {
        id: 35,
        name: "Getting Started with Terraform for Google Cloud",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb16.png",
        date: "Apr 1, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8519690",
    },
    {
        id: 36,
        name: "Develop your Google Cloud Network",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb17.png",
        date: "Apr 2, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8523043",
    },
    {
        id: 37,
        name: "Build Infrastructure with Terraform on Google Cloud",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb18.png",
        date: "Apr 4, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/8546487",
    },
    {
        id: 38,
        name: "Application Development with Cloud Run",
        provider: "Google Cloud Skills Boost",
        image: "certificates/gcsb19.png",
        date: "May 17, 2024",
        link: "https://www.cloudskillsboost.google/public_profiles/791bf115-ca30-49cc-937e-778065211a3e/badges/9060162",
    },
]
